dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
dotenv: .env
networks:
  development:
    eth_usd_price_decimals: 8
    starting_price: 4000
    verify: False
    fee: 100000000000000000
  ganache-local:
    eth_usd_price_decimals: 8
    starting_price: 4000
    verify: False
    fee: 100000000000000000
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    eth_usd_price_decimals: 8
    verify: False
    fee: 100000000000000000

wallets:
  from_key: ${PRIVATE_KEY}